const routerCategories = require( '../categories/categories.router' )
const routerCustomersInfo = require( '../customersInfo/customersInfo.router' )
const routerCustomers = require( '../customers/customers.router' )
const routerPermissions = require( '../permissions/permissions.router' )
const routerProducts = require( '../products/products.router' )
const routerProvidersInfo = require( '../providersInfo/providersInfo.router' )
const routerProviders = require( '../providers/providers.router' )
const routerPurchasesDetails = require( '../purchasesDetail/purchasesDetail.router' )
const routerPurchases = require( '../purchases/purchases.router' )
const routerRols = require( '../rols/rols.router' )
const routerSaleDetails = require( '../salesDetail/salesDetail.router' )
const routerSales = require( '../sales/sales.router' )
const routerUsers = require( '../users/users.router' )

const apiRouter = require( 'express' ).Router()

apiRouter.use( '/categories', routerCategories )
apiRouter.use( '/customers-info', routerCustomersInfo )
apiRouter.use( '/customers', routerCustomers )
apiRouter.use( '/permissions', routerPermissions )
apiRouter.use( '/products', routerProducts )
apiRouter.use( '/providers-info', routerProvidersInfo )
apiRouter.use( '/providers', routerProviders )
apiRouter.use( '/purchases-detail', routerPurchasesDetails )
apiRouter.use( '/purchases', routerPurchases )
apiRouter.use( '/rols', routerRols )
apiRouter.use( '/sales-detail', routerSaleDetails )
apiRouter.use( '/sales', routerSales )
apiRouter.use( '/users', routerUsers )

module.exports = apiRouter